#+html:<h1 align="center">Python project template</h1>
* Table of Contents
- [[#what][What]]
  - [[#features][Features]]
- [[#why][Why]]
- [[#for-whom][For Whom]]
- [[#how][How]]
  - [[#requirements][Requirements]]
  - [[#installation][Installation]]
  - [[#use][Use]]
    - [[#license][License]]
  - [[#development][Development]]
    - [[#process][Process]]
    - [[#important-decisions][Important Decisions]]
    - [[#to-do][To do]]
    - [[#contributing][Contributing]]
- [[#by-whom][By Whom]]
* What
** Features
* Why
* For Whom
* How
** Requirements
** Installation
clone git@github.com:jessenieboer/python-project-template.git
** Use

run ". gitconfig" from the project root directory

must run "direnv allow" in the project root directory (might need to make sure stuff is added to git first)

to reload environment, nix-direnv-reload

terminal commands to run to test things:
python --version - make sure it's working
which python - find interpreter location

project structure:
<project name>
- docs
- src
  - <package name>
    - __init__.py
    - <module1 name>.py
    - <module2 name>.py
- tests
  - test_<package name>
    - __init__.py
    - test_<module1 name>.py
    - test_<module2 name>.py


*** troubleshooting
i had an error where the server was trying to open a folder that didn't exist anymore and running lsp-workspace-folders-remove help get rid of it. might also be useful to set the variable
(setq lsp-session-file "/path/to/your/custom/location/.lsp-session-v1")

when running pytest:
line 1: --color=yes: command not found and restarting emacs fixed it. also closing the test file i had open fixed it

had a module not found problem: not sure exactly how it got solved, maybe 
https://www.geeksforgeeks.org/how-to-fix-the-module-not-found-error/. seems that restarting emacs helps

i had an issue where lsp headerline breadcrumbs were showing an import resolution issue (although the code worked fine). i deleted "/path/to/your/custom/location/.lsp-session-v1" and next time i opened the project emacs prompted me for something about to project folder "hello.py is not part of any project". i imported the project root and then it was fixed. before i did the import, lsp-workspace-root returned nil, afterward it returned the correct directory path. seems you can use lsp-workspace-remove-all-folders rather than deleting the session file? long story short, use the lsp-workspace commands or look a the session file when weird resolution stuff is happening
*** License
** Development
*** Process
*** Important Decisions
*** To do
*** Contributing
* By Whom
