[tool.pyright]
# pyright provides both type checking and import resolution:
  # files/directories that should be analyzed for both type checking and import resolution go in "include"
  # directories that should be on the path when resolving imports go in "extraPaths"; if nothing is here, pyright will assume all packages are at the root of the project
  # files/directories that should not be analyzed at all go in "exclude"  
exclude = [
    "**/__pycache__",
    "**/.direnv",
    "**/.pytest_cache"
]
extraPaths = ["src"]
followSymlinks = false # prevent recursion into the nix store?
include = ["bdd", "src", "tests"]
reportMissingImports = "error"
typeCheckingMode = "strict"

[tool.pytest.ini_options]
addopts = "--color=yes --tb=short"
bdd_features_base_dir = "bdd/features"
console_output_style = "progress"
log_cli = false
python_files = ["*_steps.py", "*_test.py", "test_*.py"]
python_functions = ["test_*"] # this is for running non-bdd tests
pythonpath = ["src", "tests"]
testpaths = ["bdd/steps", "tests"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
# quote-style = "single"
# indent-style = "tab"
docstring-code-format = true
